package:
  name: 'iminizinc'
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: .

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools
    - jupyter
  run:
    - python
    - jupyter

test:
  imports:
    - iminizinc

about:
  home: https://github.com/minizinc/iminizinc
  license: Mozilla Public License 2.0 (MPL 2.0)
  license_file: LICENSE.txt
  summary: IPython extensions for the MiniZinc constraint modelling language
